dist: trusty
language: python
install: pip install -r requirements.txt
script: python main_test.py
before_deploy:
- openssl aes-256-cbc -K $encrypted_244181f4f846_key -iv $encrypted_244181f4f846_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- cp app.yaml.sample app.yaml
- cat app.yaml.secret >> app.yaml
- rm app.yaml.secret secrets.tar
deploy:
  provider: gae
  project: real-connect
  no_promote: true
  skip_cleanup: true
  on:
    all_branches: true
